name: Build APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: castleengine/castle-engine:latest

    steps:
      - uses: actions/checkout@v3

      # This command compiles your project inside the Docker container
      - name: Build Android APK
        run: castle-engine package --target=android --package-format=apk --verbose

      # This uploads the finished APK so you can download it
      - uses: actions/upload-artifact@v4
        with:
          name: test-app-apk
          path: "*.apk"
